[package]
name = "aoc2022"
authors = ["Ashlin Eldridge"]
description = "Advent of Code 2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["cargo", "derive"] }
lazy_static = "1.4.0"
regex = "1.7.1"
